name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure AWS credentials (IMPORTANT)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ AKIA4X6BR242WDOVS26U }}
          aws-secret-access-key: ${{ AvNunwSHntbJ8nODNPahZdFRHbui4vmAlfEeIAnL }}
          aws-region: us-west-2   # or your AWS region

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # Initialize Terraform
      - name: Terraform Init
        working-directory: onefolder
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        working-directory: onefolder
        run: terraform plan

      # Terraform Apply (only on main branch, not PRs)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: onefolder
        run: terraform apply -auto-approve
